/*
 *  default configuration for logpoints
 *  $Id: logpoints_default.h 707 2008-03-08 10:06:44Z bkr $
 */

#ifndef __LOGPOINTS_DEFAULTS_H__
#define __LOGPOINTS_DEFAULTS_H__

#include "logpoints.h"

#ifdef LOGPOINT_RELEASE_BUILD
#define LOGPOINT_COUNT 0
#define LOGPOINT_ENABLE_DEBUG 1
#define LOGPOINT_ENABLE_TRACE 1
#define LOGPOINT_ENABLE_WARNING 1
#define LOGPOINT_ENABLE_ASSERT 1
#define LOGPOINT_ENABLE_NOTES 0
#define LOGPOINT_ENABLE_SWITCH 1
#else
#define LOGPOINT_COUNT 1
#define LOGPOINT_ENABLE_DEBUG 1
#define LOGPOINT_ENABLE_TRACE 1
#define LOGPOINT_ENABLE_WARNING 1
#define LOGPOINT_ENABLE_ASSERT 1
#define LOGPOINT_ENABLE_NOTES 1
#define LOGPOINT_ENABLE_SWITCH 1
#endif

#define LOGPOINT_FLAGS_DEBUG        ( LOGPOINT_PRIORITIZED | LOGPOINT_DEBUG )
#define LOGPOINT_FLAGS_INFO         ( LOGPOINT_PRIORITIZED | LOGPOINT_INFO )
#define LOGPOINT_FLAGS_NOTICE       ( LOGPOINT_PRIORITIZED | LOGPOINT_NOTICE )
#define LOGPOINT_FLAGS_WARNING      ( LOGPOINT_PRIORITIZED | LOGPOINT_WARNING | LOGPOINT_HARD | LOGPOINT_ACTIVE )
#define LOGPOINT_FLAGS_ERROR        ( LOGPOINT_PRIORITIZED | LOGPOINT_ERROR | LOGPOINT_HARD | LOGPOINT_ACTIVE )
#define LOGPOINT_FLAGS_CRITICAL     ( LOGPOINT_PRIORITIZED | LOGPOINT_CRITICAL | LOGPOINT_HARD | LOGPOINT_ACTIVE )
#define LOGPOINT_FLAGS_ALERT        ( LOGPOINT_PRIORITIZED | LOGPOINT_ALERT | LOGPOINT_HARD | LOGPOINT_ACTIVE )
#define LOGPOINT_FLAGS_EMERGENCY    ( LOGPOINT_PRIORITIZED | LOGPOINT_EMERGENCY | LOGPOINT_HARD | LOGPOINT_ACTIVE )

#define LOGPOINT_FLAGS_TRACE        ( LOGPOINT_DEBUG )
#define LOGPOINT_FLAGS_NOTE         ( LOGPOINT_NOTE )

#define LOGPOINT_FLAGS_SWITCH       ( LOGPOINT_SWITCH | LOGPOINT_SILENT )
#define LOGPOINT_FLAGS_DEBUG_SWITCH ( LOGPOINT_FLAGS_DEBUG | LOGPOINT_SWITCH )

#define LOGPOINT_FLAGS_ASSERT       ( LOGPOINT_EMERGENCY | LOGPOINT_ASSERT | LOGPOINT_HARD | LOGPOINT_ACTIVE )

#endif
/* __LOGPOINTS_DEFAULTS_H__ */
